{
 "title": "ETH 2.0 Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Geth",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"geth\"}"
    }
   ]
  },
  {
   "title": "Lighthouse Beacon",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"lighthouse-beacon\"}"
    }
   ]
  },
  {
   "title": "Lighthouse Validator",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"lighthouse-validator\"}"
    }
   ]
  }
 ]
}