---
- name: Set up geo-replication
  remote_user: root
  hosts: servers
  gather_facts: false

  vars:
     gluster_features_georep_mastervol: master
     gluster_features_georep_slavevol: slave
     gluster_features_georep_masternode: "{{ groups['masters'][0] }}"
     gluster_features_georep_slavenodes: "{{ groups['slaves'] }}"
  roles:
     - gluster.features
