- name: Prep storage for glusterfs...
  hosts: all
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Debug dev name
      debug:
        msg: "{{ storage_path }}"
    # - name: Try formatting
    #   block:
    #     - name: Format storage
    #       filesystem:
    #         fstype: xfs
    #         force: yes
    #         dev: '{{ storage_path }}'
    #   rescue:
    #     - name: Remove volume from system manually
    #       shell: lvremove -y vg && vgremove vg
    #     - name: Format storage
    #       filesystem:
    #         fstype: xfs
    #         force: yes
    #         dev: '{{ storage_path }}'