- name: Prep SSH key from local master
  hosts: master_local
  any_errors_fatal: true
  tasks:
    - name: Generate key
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa
    - name: Fetch the keyfile from one server to another
      fetch: 
        src: "/home/ubuntu/.ssh/id_rsa.pub"
        dest: "buffer/id_rsa.pub"
        flat: yes

- name: Transfer public key to master hosts
  hosts: master
  any_errors_fatal: true
  tasks:
    - name: Add authorized key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file','buffer/id_rsa.pub')}}"
      when: ansible_hostname != hostvars[groups['master_local'][0]]['inventory_hostname']
        