- name: Gluster Port Setup - Local
  hosts: '192.168.86.235'
  become: yes
  gather_facts: yes
  ignore_errors: true
  tasks:
    - name: Setup Gluster Brick Ports
      ufw:
        state: enabled
        rule: allow
        port: '49152:{{ 49152 + (groups["all"] | length) }}'
        proto: tcp
        from_ip: "{{ item }}"
      loop: "{{ groups['all'] }}"