- name: Remove old volumes
  hosts: master
  become: yes
  tasks:
    - name: Stop the volume
      shell: gluster --mode=script volume stop eth2vol
      ignore_errors: yes

- name: Reset mount paths and volume groups
  hosts: gluster_servers
  become: yes
  vars:
    gluster_cluster_hosts: "{{ groups['gluster_servers'] }}"
    gluster_infra_reset_mnt_paths: /mnt/brick1
    gluster_infra_reset_volume_groups: vg_eth
  roles:
    - role: './gluster_infra/roles/backend_reset'
  tasks:
    - name: Remove volume contents
      shell: rm -r /mnt/eth2
      ignore_errors: true
    - name: Remove volume mount path
      shell: rmdir /mnt/eth2
      ignore_errors: true
