- name: Copy kubelet config files
  hosts: k3s_cluster
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Copy kubelet config file
      copy:
        src: ../../manifests/kubelet-config.yaml
        dest: /home/ubuntu/kubelet-config.yaml
      register: result

- name: Copy service configurations & deploy
  hosts: master
  any_errors_fatal: true
  become: true
  roles:
    - role: kubernetes/k3s/master

- name: Copy service configurations & deploy
  hosts: nodes
  any_errors_fatal: true
  become: true
  roles:
    - role: kubernetes/k3s/node

- name: Restart k3s on server
  hosts: master
  any_errors_fatal: true
  become: yes
  tasks:
    - systemd:
        state: restarted
        name: k3s

- name: Restart k3s on nodes
  hosts: nodes
  any_errors_fatal: true
  become: yes
  tasks:
    - systemd:
        state: restarted
        name: k3s-node
        