- name: Setup K3s...
  hosts: k3s_cluster
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  roles:
    - role: kubernetes/prereq
    - role: kubernetes/download
    - role: kubernetes/raspbian
    - role: kubernetes/ubuntu
  tasks:
    - name: Pause to wait for SSH to come back online...
      pause:
        minutes: 1

- name: Copy kubelet config files
  hosts: k3s_cluster
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Copy geth service config file
      copy:
        src: ../manifests/kubelet-config.yaml
        dest: /home/ubuntu/kubelet-config.yaml

- name: Setup kubernetes master node...
  hosts: master
  any_errors_fatal: true
  become: yes
  roles:
    - role: kubernetes/k3s/master

- name: Setup kubernetes worker nodes...
  hosts: nodes
  any_errors_fatal: true
  become: yes
  roles:
    - role: kubernetes/k3s/node

# - name: Install Prometheus and Grafana
#   hosts: master 
#   become: yes
#   roles:
#     - role: kubernetes/monitoring