- name: Copy service configurations & deploy
  hosts: master
  any_errors_fatal: true
  become: true
  roles:
    - role: services/metallb
    - { role: services/glusterfs, when: storage_solution == "glusterfs" }
    - { role: services/geth, when: external_eth1 != true or standalone_geth == true }
    - { role: services/lighthouse-beacon, when: deploy_lighthouse_beacon == true }
    - { role: services/lighthouse-validator, when: deploy_lighthouse_validator == true }
    - { role: services/teku, when: deploy_teku_beacon_w_validator == true }
    - { role: services/nimbus, when: deploy_nimbus == true }
    - { role: services/prysm-beacon, when: deploy_prysm_beacon == true }
    - { role: services/prysm-validator, when: deploy_prysm_validator == true }